import { IDashboardSettingEntry } from '../interfaces'

// NOTE: step should never be less than 0.1 as we do some rounding somewhere ...
export const cssSettingsCatalog: IDashboardSettingEntry[] = [
  {
    key: 'grid-gap',
    displayName: 'Gap',
    description: 'Set the gap between widgets in the dashboard grid',
    cssProperty: '--bwj-dashboard-gap',
    step: 0.1,
    defaultUnit: 'rem',
    minValue: 0,
    defaultValue: '1.25rem',
    value: '1.25rem',
  },
  {
    key: 'widget-width',
    displayName: 'Widget Width',
    description: 'Set the min width for the widgets',
    cssProperty: '--bwj-widget-width',
    step: 0.1,
    defaultUnit: 'rem',
    minValue: 6,
    defaultValue: '21rem',
    value: '21rem',
  },
  {
    key: 'widget-border-radius',
    displayName: 'Widget Border Radius',
    description: 'Set the border radius for the widgets',
    cssProperty: '--bwj-widget-border-radius',
    step: 0.1,
    defaultUnit: 'rem',
    minValue: 0,
    defaultValue: '0.33rem',
    value: '0.33rem',
  },
  {
    key: 'widget-inner-padding-x',
    displayName: 'Widget Horiz Padding',
    description: 'Set the horizontal padding for the widgets',
    cssProperty: '--bwj-widget-inner-px',
    step: 0.1,
    defaultUnit: 'rem',
    minValue: 0,
    defaultValue: '1.0rem',
    value: '1.0rem',
  },
  {
    key: 'widget-inner-padding-y',
    displayName: 'Widget Vertical Padding',
    description: 'Set the vertical padding for the widgets',
    cssProperty: '--bwj-widget-inner-py',
    step: 0.1,
    defaultUnit: 'rem',
    minValue: 0,
    defaultValue: '0.75rem',
    value: '0.75rem',
  },
  {
    key: 'widget-header-padding-y',
    displayName: 'Widget Header Vertical Padding',
    description: 'Set the vertical padding for the widget headers',
    cssProperty: '--bwj-widget-header-py',
    step: 0.1,
    defaultUnit: 'rem',
    minValue: 0,
    defaultValue: '1.0rem',
    value: '1.0rem',
  },
  {
    key: 'widget-title-font-size',
    displayName: 'Widget Title Font Size',
    description: 'Set the font size for the widget titles',
    cssProperty: '--bwj-widget-title-size',
    step: 0.1,
    defaultUnit: 'rem',
    minValue: 0,
    defaultValue: '1.0rem',
    value: '1.0rem',
  },
]
